import hre from "hardhat";
import fs from "fs";
import path from "path";
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ethers = hre.ethers;

async function main() {
    console.log("Starting deployment process...");

    // 1. Check for Wallet
    const accounts = await hre.ethers.getSigners();
    const deployer = accounts[0];

    if (!deployer) {
        console.error("No deployer account found! Please set DEPLOYER_PRIVATE_KEY in smart-contracts/.env");
        process.exit(1);
    }

    const balance = await ethers.provider.getBalance(deployer.address);
    console.log(`Deploying with account: ${deployer.address}`);
    console.log(`Account balance: ${ethers.formatEther(balance)} ETH (or Native)`);

    // 2. Deploy MockUSDC (Skipped to preserve state)
    console.log("\nUsing existing MockUSDC...");
    // const MockUSDC = await hre.ethers.getContractFactory("MockUSDC");
    // const usdc = await MockUSDC.deploy();
    // await usdc.waitForDeployment();
    // const usdcAddress = await usdc.getAddress();
    const usdcAddress = "0x1F658C2b245926F11D487466D183D2Cc674DEF69";
    console.log(`Using existing MockUSDC at: ${usdcAddress}`);

    // 3. Deploy GroupFactory
    console.log("\nDeploying GroupFactory...");
    const GroupFactory = await hre.ethers.getContractFactory("GroupFactory");
    const factory = await GroupFactory.deploy();
    await factory.waitForDeployment();
    const factoryAddress = await factory.getAddress();
    console.log(`GroupFactory deployed to: ${factoryAddress}`);

    // 4. Output Results for Frontend
    console.log("\n--- DEPLOYMENT COMPLETE ---");
    console.log(`USDC: ${usdcAddress}`);
    console.log(`GroupFactory: ${factoryAddress}`);

    updateFrontendAddresses(factoryAddress, usdcAddress);
    copyABIs();
}

function updateFrontendAddresses(factoryAddr, usdcAddr) {
    const addressesPath = path.join(__dirname, "../../src/contracts/addresses.ts");
    const content = `// Auto-generated by deploy script
export const CONTRACT_ADDRESSES = {
    GroupFactory: "${factoryAddr}",
    USDC: "${usdcAddr}",
} as const;
`;
    fs.writeFileSync(addressesPath, content);
    console.log(`Updated ${addressesPath}`);
}

function copyABIs() {
    const abisPath = path.join(__dirname, "../../src/contracts/abis");
    if (!fs.existsSync(abisPath)) fs.mkdirSync(abisPath, { recursive: true });

    const artifactsPath = path.join(__dirname, "../artifacts/contracts");

    // Helper to copy
    const copy = (contractName, fileName) => {
        // In ESM/Hardhat, artifacts might be slightly different path relative to script
        // But usually ./artifacts/contracts/...
        const artifactPath = path.join(artifactsPath, `${contractName}.sol/${contractName}.json`);

        if (fs.existsSync(artifactPath)) {
            const artifact = JSON.parse(fs.readFileSync(artifactPath, 'utf8'));
            fs.writeFileSync(path.join(abisPath, fileName), JSON.stringify(artifact.abi, null, 2));
            console.log(`Copied ABI for ${contractName}`);
        } else {
            console.error(`Artifact not found: ${artifactPath}`);
        }
    };

    copy("GroupFactory", "GroupFactory.json");
    copy("StandardGroup", "StandardGroup.json");
    copy("AuctionGroup", "AuctionGroup.json");
    copy("MockUSDC", "USDC.json");
}

main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
});
