// Auto-generated by deploy script
export const CONTRACT_ADDRESSES = {
    GroupFactory: "0xbCbEae2Ee2132a45630225f67e475D4C8EAD7795",
    USDC: "0x1F658C2b245926F11D487466D183D2Cc674DEF69",
} as const;
