// Auto-generated by deploy script
export const CONTRACT_ADDRESSES = {
    GroupFactory: "0xeAD2caF566A418c95B9825fB888e6AB5569f7E89",
    USDC: "0x1F658C2b245926F11D487466D183D2Cc674DEF69",
} as const;
